name       : acpica-unix
version    : '20230628'
release    : 8
source     :
    - https://github.com/acpica/acpica/archive/refs/tags/R06_28_23.tar.gz : 2248799b7ca08a7711ac87d31924354ed49047507607d033bd327ba861ec4d31
license    : GPL-2.0-or-later
homepage   : https://www.intel.com/content/www/us/en/developer/topic-technology/open/acpica/overview.html
component  : programming.tools
summary    : ACPI Source Code Compiler & Disassembler
description: |
    ACPICA defines and implements a group of software components that together create an implementation of the ACPI specification for both 32-bit and 64-bit platforms.
builddeps  :
    - dos2unix
build      : |
    NOWERROR=TRUE %make
install    : |
    %make_install
